### ISSUE TITLE
Cannot reproduce Zero-Shot Accuracies for RoBERTa given in the paper

### ISSUE THREAD

**Issue by kabirahuja2431** [alontalmor/oLMpics#2]
First of all, thanks a lot for making the code and dataset accompanying the paper public.

I was running zero-shot experiments as mentioned in the paper on Age-Comparison, Always-Never, Antonym-Negation and Objects-Comparison datasets and I am unable to reproduce the accuracy values given in the paper.

My experimental setup is as follows: I first feed the 'stem' sentence to a pretrained RoBERTa-Large model and compute the LM-head scores for the [MASK] token in the input. Then, for the given options (eg. younger, older), I check the scores corresponding to each of them in the output of LM-head and see if the correct option gets a higher score. Based on this I get the following accuracy values:

Dataset | Zero-Shot Accuracy
-- | --
Age-Comparison | 0.506
Always-Never | 0.182
Antonym-Negation | 0.718
Objects-Comparison | 0.762

Is there something inherently wrong with the way I am deciding the correct option? I will appreciate any leads in the write direction.

I also tried replacing the [MASK] token with the choices one by one and computing the joint probability of the sentence as predicted by RoBERTa for each case, and noted if the sentence corresponding to the correct choice gets a higher sentence probability. I get the following results for that case.

Dataset | Zero-Shot   Accuracy
-- | --
Age-Comparison | 0.912
Always-Never | 0.264
Antonym-Negation | 0.734
Objects-Comparison | 0.574

Thanks!

**Comment by kabirahuja2431** [comment]
Apparently, I was using an older version of transformers library (2.3.0). Updating it to the most recent version (2.5.0), I am able to achieve similar results as in the paper.

I will close the issue now, Thanks!

**Comment by NamburiSrinath** [comment]
Hi @kabirahuja2431,

I am also unable to replicate the values for RoBERTa. Can you share any insights on how you are able to filter the tokens?

For RoBERTa, it has Golder, Gyounger, GOlder, GYounger? So, how to chose the choices!

Any help would be greatly appreciated, thank you
